### ISSUE TITLE
Please, provide proper bounds to packages

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix-store#175]
During bisecting in `hnix` arrived to that `hnix-store-*` do not have any bounds with packages, so `hnix-store-core 0.2.0.0` thinks it supports `saltine 0.2`, wich it does not, so needed to go back & add revisions to a number of old `hnix-store-core` versions.

Upon the next release of `hnix-store-{core,remote}`, would ask to add at least appear bounds to the packages.

```
cabal gen-bounds
...
containers           >= 0.6.5 && < 0.7,
mtl                  >= 2.2.2 && < 2.3,
attoparsec           >= 0.14.4 && < 0.15,
bytestring           >= 0.10.12 && < 0.11,
hashable             >= 1.3.5 && < 1.4,
text                 >= 1.2.4 && < 1.3,
base16-bytestring    >= 1.0.2 && < 1.1,
base64-bytestring    >= 1.2.1 && < 1.3,
cereal               >= 0.5.8 && < 0.6,
cryptonite           >= 0.29 && < 0.30,
memory               >= 0.16.0 && < 0.17,
directory            >= 1.3.6 && < 1.4,
filepath             >= 1.4.2 && < 1.5,
time                 >= 1.9.3 && < 1.10,
unix                 >= 2.7.2 && < 2.8,
lifted-base          >= 0.2.3 && < 0.3,
monad-control        >= 1.0.3 && < 1.1,
vector               >= 0.12.3 && < 0.13,
relude               >= 1.0.0 && < 1.1,
unordered-containers >= 0.2.16 && < 0.3,
saltine              >= 0.2.0 && < 0.3
```

**Comment by sorki** [comment]
The saltine bound was added in https://github.com/haskell-nix/hnix-store/commit/718685047887373f63807d9c05649d96a2fc62a6 as otherwise it tempted to fall back to older version due to bounds in some & profunctors. Couple more sensible are in place but a lot of the packages we depend on are well established, probably won't break their interface ever and if they do the CI will let us know. Thanks for the reminder!

Interestingly `cryptonite` is now archived with no replacement in sight so maybe it's time to revisit https://github.com/haskell-nix/hnix-store/issues/66 :cold_sweat:
