### ISSUE TITLE
Align hnix-store dependencies with hnix

### ISSUE THREAD

**Issue by shlevy** [haskell-nix/hnix-store#18]
We should trim down our dependencies to make it straightforward for hnix to depend on us

**Comment by imalsogreg** [comment]
`hnix-store-core` and `hnix-store-remote` have very light dependencies, except for `cryptonite` and `cryptonite`'s dependencies. 

I've removed those, in PR https://github.com/haskell-nix/hnix-store/pull/25

**Comment by Anton-Latukha** [comment]
Noted that HNix Nix closure compiles `basement`, `foundation`, `memory`.
And indeed.
Looked into it: https://hydra.nixos.org/build/132735611#tabs-build-deps

The HNix includes the whole shebang with transitive dependencies. Basically through `http-client{,-tls}` which use `memory`.

HNix currently temporarily uses `hashing` for convenience. Discovered that `hashing` in reality uses `cryptonite`. IDK through what - it is not indicated in the deps, but the Nix closure and https://hydra.nixos.org/build/132735611#tabs-build-deps clearly indicate that package depends on `cryptonite`.

Because `cryptohash-*` become unmaintained, I started the Hash subsystem refactoring to switch it to `cryptonite`, I think currently there is no escaping the switch to the current standard library in Haskell.

Meta thread about it is: https://github.com/haskell-nix/hnix-store/issues/92

**Comment by Anton-Latukha** [comment]
After the #107 and #117 the deps are minimal.

And aligned with HNix. Except for hash, which in both places needs to be switched asap, and there is no alternatives to `cryptonite`.
