### ISSUE TITLE
Compatible release of hnix-store-remote with hnix-store-core?

### ISSUE THREAD

**Issue by locallycompact** [haskell-nix/hnix-store#281]
Running into this using latest versions of releases.

```
hnix-store-remote>     • In the second argument of ‘(.)’, namely ‘storePathToRawFilePath’
hnix-store-remote>       In the first argument of ‘Data.HashSet.map’, namely
hnix-store-remote>         ‘(fromStrict . storePathToRawFilePath)’
hnix-store-remote>       In the second argument of ‘(.)’, namely
hnix-store-remote>         ‘Data.HashSet.map (fromStrict . storePathToRawFilePath)’
hnix-store-remote>     |
hnix-store-remote> 121 |   (fromStrict . storePathToRawFilePath)
hnix-store-remote>     |                 ^^^^^^^^^^^^^^^^^^^^^^
```
from: https://gitlab.horizon-haskell.net/package-sets/horizon-core/-/jobs/1461397

**Comment by sorki** [comment]
Yes, I'm aware - I have a WIP `-core`/treewide change related to derivations (and a related PR in https://github.com/Gabriella439/Haskell-Nix-Derivation-Library/pull/24) that I'm not able to finish for months now since life is getting in the way.

I hope to cut a release of all packages soon^tm, since we have 5 more sub-packages and a lot of progress.

**Comment by sorki** [comment]
Out now as `-core 0.8` and `-remote 0.7` along with new sub-packages (`-db`, `-nar`, `-json`, `-readonly`, `-tests`)
